CREATE TABLE IF NOT EXISTS public."ibtracs_historical_storm_lines" (
	"SID" VARCHAR(20) NOT NULL, 
	"SEASON" smallint NOT NULL, 
	"NUMBER" smallint NOT NULL, 
	"BASIN" VARCHAR(2) NOT NULL, 
	"SUBBASIN" VARCHAR(2) NOT NULL, 
	"NAME" VARCHAR(30) NOT NULL, 
	"ISO_TIME_START" TIMESTAMP NOT NULL, 
	"ISO_TIME_END" TIMESTAMP NOT NULL, 
	"NATURE" VARCHAR(2)[] NOT NULL, 
	geom geometry(Linestring,4326),
	PRIMARY KEY("SID", "ISO_TIME")
);
