version: '3'
services:
  geoserver:
    build:
      context: .
      args:
        - GEOSERVER_VERSION=2.22.0
        - CORS_ENABLED=true
        - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
    ports:
      - 3550:8080
    environment:
      - INSTALL_EXTENSIONS=false
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - ../data_exploration/eccc/dd.weather.gc.ca/:/opt/geoserver_data/:Z
      - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
